use_cdn: false

default:
  avatar: /img/default/avatar.jpg
  link: /img/default/link.svg
  cover: /img/default/cover.svg
  image: /img/default/image.svg

navbar:
  logo: # choose [img] or [icon + title]
    img: '' #https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title: ek1ng
  search: 想找些什么~
  menu:
    - name: 首页
      icon: fad fa-home CARROT faa-vertical
      url: /

    - name: 文章
      icon: fad fa-archive PETERRIVE faa-vertical
      url: /archives/

    - name: 标签
      icon: fad fa-folder-open CONCRETE faa-vertical
      url: /tags/

    - name: 友链
      icon: fad fa-stamp POMEGRANATE faa-vertical
      url: /friends/  

    - name: 关于
      icon: fad fa-drafting-compass WISTERIA faa-vertical
      url: /about/

    - name: 更多
      icon: fa-duotone fa-ellipsis-v
      rows:
        - name: 虫洞
          description: 十年之约，探索虫洞
          icon: fad fa-bullseye-pointer BELIZEHOLE faa-vertical
          url: https://www.foreverblog.cn/go.html

        - name: 源码
          icon: fad fa-code-merge WISTERIA faa-vertical
          url: https://github.com/ek1ng/blog


cover:
  # height_scheme: full # full, half
  title: ek1ng's blog
  subtitle: Foucs on security and web development
  background: # https://bing.ioliu.cn/v1/rand?w=1920&h=1200
  features:
    - name: 首页
      icon: fad fa-home CARROT faa-vertical
      url: /
    - name: 文章
      icon: fad fa-archive PETERRIVE faa-vertical
      url: /archives/
    - name: 标签
      icon: fad fa-folder-open CONCRETE faa-vertical
      url: /tags/
    - name: 友链
      icon: fad fa-stamp POMEGRANATE faa-vertical
      url: /friends/
    - name: 关于
      icon: fad fa-drafting-compass WISTERIA faa-vertical
      url: /about/

article:
  preview:
    # scheme: landscape # landscape
    # # pin icon for post
    # pin_icon: # https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # # auto generate title if not exist
    # auto_title: false # false, true
    # # auto generate excerpt if not exist
    # auto_excerpt: false # false, true
    # author: true
    # # show readmore button
    # readmore: auto # auto, always
      line_style: hidden
  body:
    meta_library:
      author:
        avatar: https://ek1ng-typora.oss-cn-hangzhou.aliyuncs.com/img/avatar.jpg
        name: ek1ng
        url: https://github.com/ek1ng/
      updated:
        title: '本页文档最后更新于：'


comments:
  service: valine
  valine:
    # js: https://npm.elemecdn.com/valine@1.4/dist/Valine.min.js
    path: /
    placeholder: 快来评论吧~  # 评论占位提示
    # 其他配置项按照yml格式继续填写即可 除了 [el path placeholder emojiCDN emojiMaps] 选项
    appId: ThEuM29Rc9YmToV1iVFhGyAQ-gzGzoHsz
    appKey: yOtNPLW34jnOwf7vlJuOiEFL

sidebar:
  for_page: [blogger, lastupdate, tagcloud, webinfo]
  for_post: [toc]
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /img/avatar.jpg
      shape: circle # circle, rectangle
      url: /about/
      title: ek1ng
      subtitle: 
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
    lastupdate:
      class: lastupdate
      display: [desktop]
      header:
        icon: fad fa-clock WISTERIA
        title: 随机推荐
    toc:
      display: [desktop, mobile]
      header:
        icon: fad fa-list ASBESTOS
    tagcloud:
      display: [desktop]
      header:
        title: 标签列表
        icon: fad fa-tags WISTERIA 
        url: /tags/
      max_font: 24
      min_font: 16
    webinfo:
      display: [desktop]
      header:
        icon: fad fa-award NEPHRITIS
      type:
        runtime:
          data: '2021/3/15'
        wordcount:
          unit: ''
        visitcounter:
          siteuv:
            enable: true
          sitepv:
            enable: true

tag_plugins:
  note:
    iconfont: 'Font Awesome 6 Pro'
  link:
    placeholder:  /img/default/chrome.png

site_footer:
  layout: [aplayer, social, source, analytics, copyright]
  copyright: '[Copyright © 2017-2021 Volantis Team](https://github.com/volantis-x/)'
  social:
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/020-rss.svg
      url: atom.xml
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/029-github.svg
      url: https://github.com/volantis-x/
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/010-facebook.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/018-twitter.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/045-telegram.svg
      url: /
    - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org@1.1/icon/1322024-social-media/006-youtube.svg
      url: /

plugins:
  clipboard:
    enable: true
  fontawesome: /libs/@fortawesome/fontawesome-pro/css/all.min.css
  parallax:
    enable: true
  aplayer:
    enable: true
    autoplay: false
    volume: 0.4
    order: random
    # id: 4917530132 # vol red
    # id: 4917524698 # vol blue
    # id: 76244489 # vol white
    # id: 5135845906 # for Volantis 3.0
    id: 5062959861 # TOP 30
  message:          # 音乐通知，播放、暂停、失败 时的图标
    enable: true
    icon:     # 默认图标，支持对图标添加颜色，可选值：see：/source/css/_plugins/message.styl
      default: fa-light fa-info-circle light-blue
      quection: fa-light fa-question-circle light-blue
    copyright:  # 是否在复制时弹出版权提示
      enable: false
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'fa-brands fa-creative-commons light-blue'
    aplayer:
      enable: true
      play: fa-light fa-play light-blue
      pause: fa-light fa-pause light-blue
      error: fa-light fa-exclamation-square red
  darkmode:
    enable: true
  gitter:
    room: hexo-theme-volantis/community
  wordcount:
    enable: true

analytics:
  busuanzi: /libs/busuanzi/js/busuanzi.pure.mini.js #https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js

custom_css:
  cursor:
    enable: true
  font_smoothing: true
  sidebar:
    effect: [shadow] # [shadow, floatable, blur]
  body:
    effect: [shadow] # [shadow, floatable, blur]
  fontfamily:
    logofont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'Dosis, "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Dosis'
      url: https://cdn.jsdelivr.net/gh/volantis-x/cdn-fonts@20.5.30/Dosis/Dosis-Medium.ttf
      weight: normal
      style: normal

rightmenu:
  enable: true
  faicon: fa-duotone PETERRIVE
  print:
    icon: fa-duotone fa-print TURQUOISE
  darkmode:
    icon: fa-duotone fa-eclipse-alt WISTERIA
  reading:
    icon: fa-duotone fa-book-open EMERALD
  help:
    icon: fa-duotone fa-question EMERALD
  examples:
    icon: fa-duotone fa-rss PETERRIVE
  contributors:
    icon: fa-duotone fa-fan fa-spin AMETHYST
  source_docs:
    icon: fa-duotone fa-code-branch WETASPHALT
  source_theme:
    icon: fa-duotone fa-file-code CONCRETE

pages:
  # 友链页面配置
  friends:
    layout_scheme: simple # simple: 简单布局, traditional: 传统布局